In [1]:
import os
import numpy


In [2]:
pwd

'C:\\Users\\johnt\\Desktop\\cms-workshop\\data\\data'

In [5]:
file_location=os.path.join('water.xyz')
print(file_location)

water.xyz


In [10]:
xyz_file=numpy.genfromtxt(file_location, skip_header=2, dtype='unicode')
print(xyz_file)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [22]:
symbols=xyz_file[:,0]
print(symbols)
coordinates=xyz_file[:,1:4]
coordinates=coordinates.astype(numpy.float)
print(coordinates)

['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [38]:
howmany=len(symbols)
for i in range(0,howmany):
    if (i+1)<howmany:
        dx2=(coordinates[i,0]-coordinates[i+1,0])**2
        dy2=(coordinates[i,1]-coordinates[i+1,1])**2
        dz2=(coordinates[i,2]-coordinates[i+1,2])**2
        dr=(dx2+dy2+dz2)**0.5
        print(F'{symbols[i]} to {symbols[i+1]}', dr)
    else:
        dx2=(coordinates[i,0]-coordinates[0,0])**2
        dy2=(coordinates[i,1]-coordinates[0,1])**2
        dz2=(coordinates[i,2]-coordinates[0,2])**2
        dr=(dx2+dy2+dz2)**0.5
        print(F'{symbols[i]} to {symbols[0]}', dr)    

O to H1 0.9690005374652793
H1 to H2 1.52693633514957
H2 to O 0.9690003348647513


In [42]:
import os
import numpy
print(os.getcwd())
file_location=os.path.join('water.xyz')
print(file_location)
xyz_file=numpy.genfromtxt(file_location, skip_header=2, dtype='unicode')
print(xyz_file)
symbols=xyz_file[:,0]
print(symbols)
coordinates=xyz_file[:,1:4]
coordinates=coordinates.astype(numpy.float)
print(coordinates)
howmany=len(symbols)
for i in range(0,howmany):
    for k in range(0,howmany-1):
        if (i+1)<howmany:
            dx2=(coordinates[i,0]-coordinates[i+k,0])**2
            dy2=(coordinates[i,1]-coordinates[i+k,1])**2
            dz2=(coordinates[i,2]-coordinates[i+k,2])**2
            dr=(dx2+dy2+dz2)**0.5
            print(F'{symbols[i]} to {symbols[i+1]}', dr)
        else:
            dx2=(coordinates[i,0]-coordinates[0,0])**2
            dy2=(coordinates[i,1]-coordinates[0,1])**2
            dz2=(coordinates[i,2]-coordinates[0,2])**2
            dr=(dx2+dy2+dz2)**0.5
            print(F'{symbols[i]} to {symbols[0]}', dr)    

C:\Users\johnt\Desktop\cms-workshop\data\data
water.xyz
[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]
['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
O to H1 0.0
O to H1 0.9690005374652793
H1 to H2 0.0
H1 to H2 1.52693633514957
H2 to O 0.9690003348647513
H2 to O 0.9690003348647513


In [49]:
#Most Efficient
import os
import numpy
print(os.getcwd())
file_location=os.path.join('water.xyz')
print(file_location)
xyz_file=numpy.genfromtxt(file_location, skip_header=2, dtype='unicode')
print(xyz_file)
symbols=xyz_file[:,0]
print(symbols)
coordinates=xyz_file[:,1:4]
coordinates=coordinates.astype(numpy.float)
print(coordinates)
howmany=len(symbols)
for i in range(0,howmany):
    for k in range(1,howmany-i):
            dx2=(coordinates[i,0]-coordinates[i+k,0])**2
            dy2=(coordinates[i,1]-coordinates[i+k,1])**2
            dz2=(coordinates[i,2]-coordinates[i+k,2])**2
            dr=(dx2+dy2+dz2)**0.5
            print(F'{symbols[i]} to {symbols[i+k]}', dr)


C:\Users\johnt\Desktop\cms-workshop\data\data
water.xyz
[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]
['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
O to H1 0.9690005374652793
O to H2 0.9690003348647513
H1 to H2 1.52693633514957


In [53]:
import os
import numpy
print(os.getcwd())
file_location=os.path.join('water.xyz')
print(file_location)
xyz_file=numpy.genfromtxt(file_location, skip_header=2, dtype='unicode')
print(xyz_file)
symbols=xyz_file[:,0]
print(symbols)
coordinates=xyz_file[:,1:4]
coordinates=coordinates.astype(numpy.float)
print(coordinates)
howmany=len(symbols)
for i in range(0,howmany):
    for k in range(1,howmany-i):
        dx2=(coordinates[i,0]-coordinates[i+k,0])**2
        dy2=(coordinates[i,1]-coordinates[i+k,1])**2
        dz2=(coordinates[i,2]-coordinates[i+k,2])**2
        dr=(dx2+dy2+dz2)**0.5
        if dr<1.5:    
            print(F'The bond between {symbols[i]} to {symbols[i+k]} has a distance of ', dr)
        else:
            print(F'There is no bond between {symbols[i]} to {symbols[i+k]}. The distance between the two atoms is ', dr)


C:\Users\johnt\Desktop\cms-workshop\data\data
water.xyz
[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]
['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
The bond between O to H1 has a distance of  0.9690005374652793
The bond between O to H2 has a distance of  0.9690003348647513
There is no bond between H1 to H2. The distance between the two atoms is  1.52693633514957


In [55]:
#function is a piece of code that does one particular task

In [80]:
def drbtwnatoms(filename_string):
    import os
    import numpy
    print(os.getcwd())
    file_location=os.path.join(filename_string)
    print(file_location)
    xyz_file=numpy.genfromtxt(file_location, skip_header=2, dtype='unicode')
    print(xyz_file)
    symbols=xyz_file[:,0]
    print(symbols)
    coordinates=xyz_file[:,1:4]
    coordinates=coordinates.astype(numpy.float)
    print(coordinates)
    howmany=len(symbols)
    for i in range(0,howmany):
        for k in range(1,howmany-i):
            dx2=(coordinates[i,0]-coordinates[i+k,0])**2
            dy2=(coordinates[i,1]-coordinates[i+k,1])**2
            dz2=(coordinates[i,2]-coordinates[i+k,2])**2
            dr=(dx2+dy2+dz2)**0.5
            if dr<1.5:    
                print(F'The bond between {symbols[i]} to {symbols[i+k]} has a distance of ', dr)
            else:
                print(F'There is no bond between {symbols[i]} to {symbols[i+k]}. The distance between the two atoms is ', dr)
                


In [77]:
drbtwnatoms

<function __main__.drbtwnatoms(filename_string)>

In [81]:
drbtwnatoms('water.xyz')

C:\Users\johnt\Desktop\cms-workshop\data\data
water.xyz
[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]
['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
The bond between O to H1 has a distance of  0.9690005374652793
The bond between O to H2 has a distance of  0.9690003348647513
There is no bond between H1 to H2. The distance between the two atoms is  1.52693633514957


In [63]:
drbtwnatoms

<function __main__.drbtwnatoms(filename)>

In [67]:
drbtwnatoms

<function __main__.drbtwnatoms(filename_string)>

In [70]:
drbtwnatoms(water.xyz)

NameError: name 'water' is not defined

def function_name(parameters):
    code
    return Value_to_return

In [91]:
def drbtwnatoms(filename_string):
    import os
    import numpy
    print(os.getcwd())
    file_location=os.path.join(filename_string)
    print(file_location)
    xyz_file=numpy.genfromtxt(file_location, skip_header=2, dtype='unicode')
    print(xyz_file)
    symbols=xyz_file[:,0]
    print(symbols)
    coordinates=xyz_file[:,1:4]
    coordinates=coordinates.astype(numpy.float)
    print(coordinates)
    howmany=len(symbols)
    distances=[]
    for i in range(0,howmany):
        for k in range(1,howmany-i):
            dx2=(coordinates[i,0]-coordinates[i+k,0])**2
            dy2=(coordinates[i,1]-coordinates[i+k,1])**2
            dz2=(coordinates[i,2]-coordinates[i+k,2])**2
            dr=(dx2+dy2+dz2)**0.5
            if dr<1.5:    
                distances.append(F'The bond between {symbols[i]} to {symbols[i+k]} has a distance of {dr}')
            else:
                distances.append(F'There is no bond between {symbols[i]} to {symbols[i+k]}. The distance between the two atoms is {dr}')
    return distances

In [92]:
drbtwnatoms('water.xyz')

C:\Users\johnt\Desktop\cms-workshop\data\data
water.xyz
[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]
['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


['The bond between O to H1 has a distance of 0.9690005374652793',
 'The bond between O to H2 has a distance of 0.9690003348647513',
 'There is no bond between H1 to H2. The distance between the two atoms is 1.52693633514957']

In [110]:
def calculate_distance(coords1,coords2):
    """
    Documentation string.
    This function accepts coords of 2 atoms, and calculates distance between atoms.
    """
    dx2=(coords1[0]-coords2[0])**2
    dy2=(coords1[1]-coords2[1])**2
    dz2=(coords1[2]-coords2[2])**2
    dr=(dx2+dy2+dz2)**0.5
    return dr


In [126]:
def bondcheck(distance):
    if 0<distance<1.5:
        return True
    else:
        return False

In [127]:
import os
import numpy
print(os.getcwd())
file_location=os.path.join('water.xyz')
print(file_location)
xyz_file=numpy.genfromtxt(file_location, skip_header=2, dtype='unicode')
print(xyz_file)
symbols=xyz_file[:,0]
print(symbols)
coordinates=xyz_file[:,1:4]
coordinates=coordinates.astype(numpy.float)
print(coordinates)
howmany=len(symbols)
for i in range(0,howmany):
    for k in range(1,howmany-i):
        howfar=calculate_distance(coordinates[i],coordinates[i+k])
        if howfar<1.5:    
            print(F'The bond between {symbols[i]} to {symbols[i+k]} has a distance of {howfar}')
        else:
            print(F'There is no bond between {symbols[i]} to {symbols[i+k]}. The distance between the two atoms is {howfar}')

C:\Users\johnt\Desktop\cms-workshop\data\data
water.xyz
[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]
['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
The bond between O to H1 has a distance of 0.9690005374652793
The bond between O to H2 has a distance of 0.9690003348647513
There is no bond between H1 to H2. The distance between the two atoms is 1.52693633514957


In [112]:
help(calculate_distance)

Help on function calculate_distance in module __main__:

calculate_distance(coords1, coords2)
    Documentation string.
    This function accepts coords of 2 atoms, and calculates distance between atoms.



In [119]:
bondcheck(3)

'False'

In [123]:
import os
import numpy
print(os.getcwd())
file_location=os.path.join('water.xyz')
print(file_location)
xyz_file=numpy.genfromtxt(file_location, skip_header=2, dtype='unicode')
print(xyz_file)
symbols=xyz_file[:,0]
print(symbols)
coordinates=xyz_file[:,1:4]
coordinates=coordinates.astype(numpy.float)
print(coordinates)
howmany=len(symbols)
for i in range(0,howmany):
    for k in range(1,howmany-i):
        howfar=calculate_distance(coordinates[i],coordinates[i+k])
        if bondcheck(howfar) is True:    
            print(F'The bond between {symbols[i]} to {symbols[i+k]} has a distance of {howfar}')
        else:
            print(F'There is no bond between {symbols[i]} to {symbols[i+k]}. The distance between the two atoms is {howfar}')

C:\Users\johnt\Desktop\cms-workshop\data\data
water.xyz
[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]
['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
The bond between O to H1 has a distance of 0.9690005374652793
The bond between O to H2 has a distance of 0.9690003348647513
There is no bond between H1 to H2. The distance between the two atoms is 1.52693633514957


In [142]:
def bondcheck(distance, minimum=0, maximum=1.5): #The equal sign allows for a default.
    if minimum<distance<maximum:
        return True
    else:
        return False

In [136]:
bondcheck(4.5,4,5)

True

In [143]:
import os
import numpy
print(os.getcwd())
file_location=os.path.join('water.xyz')
print(file_location)
xyz_file=numpy.genfromtxt(file_location, skip_header=2, dtype='unicode')
print(xyz_file)
symbols=xyz_file[:,0]
print(symbols)
coordinates=xyz_file[:,1:4]
coordinates=coordinates.astype(numpy.float)
print(coordinates)
howmany=len(symbols)
for i in range(0,howmany):
    for k in range(1,howmany-i):
        howfar=calculate_distance(coordinates[i],coordinates[i+k])
        if bondcheck(howfar) is True:    
            print(F'The bond between {symbols[i]} to {symbols[i+k]} has a distance of {howfar}')
        else:
            print(F'There is no bond between {symbols[i]} to {symbols[i+k]}. The distance between the two atoms is {howfar}')

C:\Users\johnt\Desktop\cms-workshop\data\data
water.xyz
[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]
['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
The bond between O to H1 has a distance of 0.9690005374652793
The bond between O to H2 has a distance of 0.9690003348647513
There is no bond between H1 to H2. The distance between the two atoms is 1.52693633514957


In [ ]:
import os
import numpy
import sys

def calculate_distance(coords1,coords2):
    """
    Documentation string.
    This function accepts coords of 2 atoms, and calculates distance between atoms.
    """
    dx2=(coords1[0]-coords2[0])**2
    dy2=(coords1[1]-coords2[1])**2
    dz2=(coords1[2]-coords2[2])**2
    dr=(dx2+dy2+dz2)**0.5
    return dr

def bondcheck(distance):
    if 0<distance<1.5:
        return True
    else:
        return False
#argv 0 is program, argv 1 is the argument. argv1 needs to be the whole path of the file that you want as the argument.
file_location=os.path.join('water.xyz')
print(file_location)
xyz_file=numpy.genfromtxt(file_location, skip_header=2, dtype='unicode')
print(xyz_file)
symbols=xyz_file[:,0]
print(symbols)
coordinates=xyz_file[:,1:4]
coordinates=coordinates.astype(numpy.float)
print(coordinates)
howmany=len(symbols)
for i in range(0,howmany):
    for k in range(1,howmany-i):
        howfar=calculate_distance(coordinates[i],coordinates[i+k])
        if bondcheck(howfar) is True:
            print(F'The bond between {symbols[i]} to {symbols[i+k]} has a distance of {howfar}')
        else:
            print(F'There is no bond between {symbols[i]} to {symbols[i+k]}. The distance between the two atoms is {howfar}')
